// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh_hf2O1K6xE4EIgoUqpkKO8NOPpKuZyM',
    appId: '1:371289133334:web:c892849b79180fa8ba0037',
    messagingSenderId: '371289133334',
    projectId: 'todo-8c8ee',
    authDomain: 'todo-8c8ee.firebaseapp.com',
    storageBucket: 'todo-8c8ee.appspot.com',
    measurementId: 'G-XJRQPC3CDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgd-3AzSzTZ4dImMoaWnZYGNDXnZcTsag',
    appId: '1:371289133334:android:ff25a530fb642d38ba0037',
    messagingSenderId: '371289133334',
    projectId: 'todo-8c8ee',
    storageBucket: 'todo-8c8ee.appspot.com',
  );
}
