// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8cWeZ2q0Bl7z7xAv3dD4Zht_jooiFW9g',
    appId: '1:636673891456:web:8ee5525bb46fe18fb35a65',
    messagingSenderId: '636673891456',
    projectId: 'image-picker-43779',
    authDomain: 'image-picker-43779.firebaseapp.com',
    storageBucket: 'image-picker-43779.firebasestorage.app',
    measurementId: 'G-4SWYHEWSX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeG1oAlPaO-3DBudalHIZ8DeIo0RL8UiU',
    appId: '1:636673891456:android:d7c37533220d9bd8b35a65',
    messagingSenderId: '636673891456',
    projectId: 'image-picker-43779',
    storageBucket: 'image-picker-43779.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAigFHD6H7Bvr1zB6Vf9FrJRXOcDhEqUCE',
    appId: '1:636673891456:ios:7371632cd2aa321cb35a65',
    messagingSenderId: '636673891456',
    projectId: 'image-picker-43779',
    storageBucket: 'image-picker-43779.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAigFHD6H7Bvr1zB6Vf9FrJRXOcDhEqUCE',
    appId: '1:636673891456:ios:7371632cd2aa321cb35a65',
    messagingSenderId: '636673891456',
    projectId: 'image-picker-43779',
    storageBucket: 'image-picker-43779.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8cWeZ2q0Bl7z7xAv3dD4Zht_jooiFW9g',
    appId: '1:636673891456:web:6470bff9e4ffe440b35a65',
    messagingSenderId: '636673891456',
    projectId: 'image-picker-43779',
    authDomain: 'image-picker-43779.firebaseapp.com',
    storageBucket: 'image-picker-43779.firebasestorage.app',
    measurementId: 'G-2V3Y0T9P3Z',
  );
}
